### ISSUE TITLE
Age text box accepting letters

### ISSUE THREAD

**Issue by King-Tav** [avmturo/Dependable_Systems_EGFR#2]
Age text box accepts letters and does not prompt users to address this problem. It would be expected that it would only accept numerical characters.

**Comment by avmturo** [comment]
Issue has been resolved. Added validation in input, making sure only integers between 189-120 can be used for calculation

**Comment by avmturo** [comment]
+ appending previous comment. No character/string values can be entered into the field. 18-120 correction from 189-120
